<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JACOBPHILLIP" tests="204" failures="143" timestamp="20 Jul 2016 03:02:09 GMT" time="0.176" errors="0">
  <testcase name="testAdd" time="0.0" classname="Test_1"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testAddAfter_invalidElement()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testAddAfter_invalidElement()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddToFront" time="0.001" classname="Test_1"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_1"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testAdd_invalidIndex(int)[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testAdd_invalidIndex(int)[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testAdd_invalidIndex(int)[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testAdd_invalidIndex(int)[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_1"/>
  <testcase name="testContains_invalidElement" time="0.001" classname="Test_1"/>
  <testcase name="testFirst" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testFirst()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testFirst()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet" time="0.0" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_1.testGet(Test_1.java:234)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_1.testIndexOf_invalidElement(Test_1.java:244)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIsEmpty" time="0.0" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.isEmpty(TestCase.java:138)
	at Test_1.testIsEmpty(Test_1.java:122)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIsEmpty -->
  <testcase name="testIterator" time="0.0" classname="Test_1"/>
  <testcase name="testLast" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testLast()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testLast()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testRemoveFirst()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testRemoveFirst()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testRemoveLast()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testRemoveLast()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.0" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_1.testRemove_invalidElement(Test_1.java:82)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.001" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_1.testRemove_invalidIndex(Test_1.java:202)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testSet" time="0.0" classname="Test_1">
    <failure type="org.testng.TestException" message="
Method Test_1.testSet()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_1.testSet()[pri:0, instance:Test_1@548a9f61] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet -->
  <testcase name="testSize" time="0.0" classname="Test_1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_1.testSize(Test_1.java:132)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_2"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_2">
    <failure type="org.testng.TestException" message="
Method Test_2.testAddAfter_invalidElement()[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_2.testAddAfter_invalidElement()[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddAfter_validElement" time="0.001" classname="Test_2"/>
  <testcase name="testAddToFront" time="0.0" classname="Test_2"/>
  <testcase name="testAddToRear" time="0.001" classname="Test_2"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_2">
    <failure type="org.testng.TestException" message="
Method Test_2.testAdd_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_2.testAdd_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_2">
    <failure type="org.testng.TestException" message="
Method Test_2.testAdd_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_2.testAdd_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_2"/>
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_2"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_2"/>
  <testcase name="testContains_validElement" time="0.001" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.contains(TestCase.java:127)
	at Test_2.testContains_validElement(Test_2.java:132)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testContains_validElement -->
  <testcase name="testFirst" time="0.001" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.first(TestCase.java:104)
	at Test_2.testFirst(Test_2.java:112)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet_invalidIndex" time="0.001" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_2.testGet_invalidIndex(Test_2.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_invalidIndex" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_2.testGet_invalidIndex(Test_2.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_validIndex" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_2.testGet_validIndex(Test_2.java:293)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_validIndex -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_2.testIndexOf_invalidElement(Test_2.java:323)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIndexOf_validElement" time="0.0" classname="Test_2"/>
  <testcase name="testIsEmpty" time="0.0" classname="Test_2"/>
  <testcase name="testIterator" time="0.0" classname="Test_2">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_2.testIterator(Test_2.java:173)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.last(TestCase.java:115)
	at Test_2.testLast(Test_2.java:122)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.001" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeFirst(TestCase.java:71)
	at Test_2.testRemoveFirst(Test_2.java:72)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeLast(TestCase.java:82)
	at Test_2.testRemoveLast(Test_2.java:82)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_2.testRemove_invalidElement(Test_2.java:102)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.001" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_2.testRemove_invalidIndex(Test_2.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_2.testRemove_invalidIndex(Test_2.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_validElement" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_2.testRemove_validElement(Test_2.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validElement -->
  <testcase name="testRemove_validIndex" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_2.testRemove_validIndex(Test_2.java:243)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_2">
    <failure type="org.testng.TestException" message="
Method Test_2.testSet_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_2.testSet_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_2">
    <failure type="org.testng.TestException" message="
Method Test_2.testSet_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_2.testSet_invalidIndex(int)[pri:0, instance:Test_2@1753acfe] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_validIndex" time="0.0" classname="Test_2"/>
  <testcase name="testSize" time="0.0" classname="Test_2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_2.testSize(Test_2.java:162)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_3"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_3">
    <failure type="org.testng.TestException" message="
Method Test_3.testAddAfter_invalidElement()[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_3.testAddAfter_invalidElement()[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddAfter_validElement" time="0.0" classname="Test_3"/>
  <testcase name="testAddToFront" time="0.001" classname="Test_3"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_3"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_3">
    <failure type="org.testng.TestException" message="
Method Test_3.testAdd_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_3.testAdd_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_3">
    <failure type="org.testng.TestException" message="
Method Test_3.testAdd_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_3.testAdd_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_3"/>
  <testcase name="testAdd_validIndex" time="0.001" classname="Test_3"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_3"/>
  <testcase name="testContains_validElement" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.contains(TestCase.java:127)
	at Test_3.testContains_validElement(Test_3.java:132)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testContains_validElement -->
  <testcase name="testFirst" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.first(TestCase.java:104)
	at Test_3.testFirst(Test_3.java:112)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet_invalidIndex" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_3.testGet_invalidIndex(Test_3.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_invalidIndex" time="0.001" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_3.testGet_invalidIndex(Test_3.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_validIndex" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_3.testGet_validIndex(Test_3.java:293)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_validIndex -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_3.testIndexOf_invalidElement(Test_3.java:323)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIndexOf_validElement" time="0.0" classname="Test_3"/>
  <testcase name="testIsEmpty" time="0.001" classname="Test_3"/>
  <testcase name="testIterator" time="0.0" classname="Test_3">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_3.testIterator(Test_3.java:173)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.last(TestCase.java:115)
	at Test_3.testLast(Test_3.java:122)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeFirst(TestCase.java:71)
	at Test_3.testRemoveFirst(Test_3.java:72)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeLast(TestCase.java:82)
	at Test_3.testRemoveLast(Test_3.java:82)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_3.testRemove_invalidElement(Test_3.java:102)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_3.testRemove_invalidIndex(Test_3.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_invalidIndex" time="0.001" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_3.testRemove_invalidIndex(Test_3.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_validElement" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_3.testRemove_validElement(Test_3.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validElement -->
  <testcase name="testRemove_validIndex" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_3.testRemove_validIndex(Test_3.java:243)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_3">
    <failure type="org.testng.TestException" message="
Method Test_3.testSet_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_3.testSet_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_invalidIndex" time="0.001" classname="Test_3">
    <failure type="org.testng.TestException" message="
Method Test_3.testSet_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_3.testSet_invalidIndex(int)[pri:0, instance:Test_3@7c16905e] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_validIndex" time="0.0" classname="Test_3"/>
  <testcase name="testSize" time="0.0" classname="Test_3">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_3.testSize(Test_3.java:162)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_4"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_4">
    <failure type="org.testng.TestException" message="
Method Test_4.testAddAfter_invalidElement()[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_4.testAddAfter_invalidElement()[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddAfter_validElement" time="0.0" classname="Test_4"/>
  <testcase name="testAddToFront" time="0.0" classname="Test_4"/>
  <testcase name="testAddToRear" time="0.001" classname="Test_4"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_4">
    <failure type="org.testng.TestException" message="
Method Test_4.testAdd_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_4.testAdd_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_4">
    <failure type="org.testng.TestException" message="
Method Test_4.testAdd_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_4.testAdd_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_4"/>
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_4"/>
  <testcase name="testContains_invalidElement" time="0.001" classname="Test_4"/>
  <testcase name="testContains_validElement" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.contains(TestCase.java:127)
	at Test_4.testContains_validElement(Test_4.java:132)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testContains_validElement -->
  <testcase name="testFirst" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.first(TestCase.java:104)
	at Test_4.testFirst(Test_4.java:112)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet_invalidIndex" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_4.testGet_invalidIndex(Test_4.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_invalidIndex" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_4.testGet_invalidIndex(Test_4.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_validIndex" time="0.001" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_4.testGet_validIndex(Test_4.java:293)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_validIndex -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_4.testIndexOf_invalidElement(Test_4.java:323)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIndexOf_validElement" time="0.003" classname="Test_4"/>
  <testcase name="testIsEmpty" time="0.0" classname="Test_4"/>
  <testcase name="testIterator" time="0.001" classname="Test_4">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_4.testIterator(Test_4.java:173)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.last(TestCase.java:115)
	at Test_4.testLast(Test_4.java:122)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeFirst(TestCase.java:71)
	at Test_4.testRemoveFirst(Test_4.java:72)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeLast(TestCase.java:82)
	at Test_4.testRemoveLast(Test_4.java:82)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.001" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_4.testRemove_invalidElement(Test_4.java:102)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_4.testRemove_invalidIndex(Test_4.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_4.testRemove_invalidIndex(Test_4.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_validElement" time="0.001" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_4.testRemove_validElement(Test_4.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validElement -->
  <testcase name="testRemove_validIndex" time="0.001" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_4.testRemove_validIndex(Test_4.java:243)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_4">
    <failure type="org.testng.TestException" message="
Method Test_4.testSet_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_4.testSet_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_4">
    <failure type="org.testng.TestException" message="
Method Test_4.testSet_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_4.testSet_invalidIndex(int)[pri:0, instance:Test_4@2a2d45ba] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_validIndex" time="0.0" classname="Test_4"/>
  <testcase name="testSize" time="0.0" classname="Test_4">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_4.testSize(Test_4.java:162)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_5"/>
  <testcase name="testAddAfter_invalidElement" time="0.001" classname="Test_5">
    <failure type="org.testng.TestException" message="
Method Test_5.testAddAfter_invalidElement()[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_5.testAddAfter_invalidElement()[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddAfter_validElement" time="0.0" classname="Test_5"/>
  <testcase name="testAddToFront" time="0.001" classname="Test_5"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_5"/>
  <testcase name="testAdd_invalidIndex" time="0.001" classname="Test_5">
    <failure type="org.testng.TestException" message="
Method Test_5.testAdd_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_5.testAdd_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_5">
    <failure type="org.testng.TestException" message="
Method Test_5.testAdd_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_5.testAdd_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.001" classname="Test_5"/>
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_5"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_5"/>
  <testcase name="testContains_validElement" time="0.001" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.contains(TestCase.java:127)
	at Test_5.testContains_validElement(Test_5.java:132)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testContains_validElement -->
  <testcase name="testFirst" time="0.003" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.first(TestCase.java:104)
	at Test_5.testFirst(Test_5.java:112)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet_invalidIndex" time="0.001" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_5.testGet_invalidIndex(Test_5.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_invalidIndex" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_5.testGet_invalidIndex(Test_5.java:303)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_invalidIndex -->
  <testcase name="testGet_validIndex" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_5.testGet_validIndex(Test_5.java:293)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet_validIndex -->
  <testcase name="testIndexOf_invalidElement" time="0.001" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_5.testIndexOf_invalidElement(Test_5.java:323)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIndexOf_validElement" time="0.0" classname="Test_5"/>
  <testcase name="testIsEmpty" time="0.0" classname="Test_5"/>
  <testcase name="testIterator" time="0.0" classname="Test_5">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_5.testIterator(Test_5.java:173)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.001" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.last(TestCase.java:115)
	at Test_5.testLast(Test_5.java:122)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeFirst(TestCase.java:71)
	at Test_5.testRemoveFirst(Test_5.java:72)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.removeLast(TestCase.java:82)
	at Test_5.testRemoveLast(Test_5.java:82)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_5.testRemove_invalidElement(Test_5.java:102)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_5.testRemove_invalidIndex(Test_5.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_5.testRemove_invalidIndex(Test_5.java:253)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testRemove_validElement" time="0.001" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_5.testRemove_validElement(Test_5.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validElement -->
  <testcase name="testRemove_validIndex" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_5.testRemove_validIndex(Test_5.java:243)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_validIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_5">
    <failure type="org.testng.TestException" message="
Method Test_5.testSet_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_5.testSet_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_invalidIndex" time="0.0" classname="Test_5">
    <failure type="org.testng.TestException" message="
Method Test_5.testSet_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_5.testSet_invalidIndex(int)[pri:0, instance:Test_5@2a5ca609] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet_invalidIndex -->
  <testcase name="testSet_validIndex" time="0.0" classname="Test_5"/>
  <testcase name="testSize" time="0.0" classname="Test_5">
    <failure type="java.lang.AssertionError" message="expected [1] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_5.testSize(Test_5.java:162)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_6"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testAddAfter_invalidElement()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testAddAfter_invalidElement()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddToFront" time="0.0" classname="Test_6"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_6"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testAdd_invalidIndex(int)[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testAdd_invalidIndex(int)[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testAdd_invalidIndex(int)[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testAdd_invalidIndex(int)[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.001" classname="Test_6"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_6"/>
  <testcase name="testFirst" time="0.001" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testFirst()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testFirst()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet" time="0.0" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_6.testGet(Test_6.java:239)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_6.testIndexOf_invalidElement(Test_6.java:249)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIsEmpty" time="0.001" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.isEmpty(TestCase.java:138)
	at Test_6.testIsEmpty(Test_6.java:126)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIsEmpty -->
  <testcase name="testIterator" time="0.002" classname="Test_6">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_6.testIterator(Test_6.java:147)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.001" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testLast()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testLast()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testRemoveFirst()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testRemoveFirst()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.0" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testRemoveLast()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testRemoveLast()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.002" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_6.testRemove_invalidElement(Test_6.java:86)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_6.testRemove_invalidIndex(Test_6.java:207)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testSet" time="0.001" classname="Test_6">
    <failure type="org.testng.TestException" message="
Method Test_6.testSet()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_6.testSet()[pri:0, instance:Test_6@20e2cbe0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet -->
  <testcase name="testSize" time="0.0" classname="Test_6">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_6.testSize(Test_6.java:136)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_7"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testAddAfter_invalidElement()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testAddAfter_invalidElement()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddToFront" time="0.003" classname="Test_7"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_7"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testAdd_invalidIndex(int)[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testAdd_invalidIndex(int)[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testAdd_invalidIndex(int)[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testAdd_invalidIndex(int)[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_7"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_7"/>
  <testcase name="testFirst" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testFirst()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testFirst()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet" time="0.0" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_7.testGet(Test_7.java:239)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet -->
  <testcase name="testIndexOf_invalidElement" time="0.0" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_7.testIndexOf_invalidElement(Test_7.java:249)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIsEmpty" time="0.0" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.isEmpty(TestCase.java:138)
	at Test_7.testIsEmpty(Test_7.java:126)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIsEmpty -->
  <testcase name="testIterator" time="0.001" classname="Test_7">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_7.testIterator(Test_7.java:147)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testLast()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testLast()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testRemoveFirst()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testRemoveFirst()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.003" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testRemoveLast()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testRemoveLast()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.001" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_7.testRemove_invalidElement(Test_7.java:86)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.0" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_7.testRemove_invalidIndex(Test_7.java:207)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testSet" time="0.0" classname="Test_7">
    <failure type="org.testng.TestException" message="
Method Test_7.testSet()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_7.testSet()[pri:0, instance:Test_7@68be2bc2] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet -->
  <testcase name="testSize" time="0.0" classname="Test_7">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_7.testSize(Test_7.java:136)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
  <testcase name="testAdd" time="0.0" classname="Test_8"/>
  <testcase name="testAddAfter_invalidElement" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testAddAfter_invalidElement()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.util.NoSuchElementException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testAddAfter_invalidElement()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.util.NoSuchElementException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAddAfter_invalidElement -->
  <testcase name="testAddToFront" time="0.0" classname="Test_8"/>
  <testcase name="testAddToRear" time="0.0" classname="Test_8"/>
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testAdd_invalidIndex(int)[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testAdd_invalidIndex(int)[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_invalidIndex" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testAdd_invalidIndex(int)[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testAdd_invalidIndex(int)[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_invalidIndex -->
  <testcase name="testAdd_validIndex" time="0.0" classname="Test_8"/>
  <testcase name="testContains_invalidElement" time="0.0" classname="Test_8"/>
  <testcase name="testFirst" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testFirst()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testFirst()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testFirst -->
  <testcase name="testGet" time="0.002" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.get(TestCase.java:215)
	at Test_8.testGet(Test_8.java:241)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGet -->
  <testcase name="testIndexOf_invalidElement" time="0.001" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
	at TestCase.indexOf(TestCase.java:227)
	at Test_8.testIndexOf_invalidElement(Test_8.java:251)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIndexOf_invalidElement -->
  <testcase name="testIsEmpty" time="0.0" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestCase.isEmpty(TestCase.java:138)
	at Test_8.testIsEmpty(Test_8.java:127)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testIsEmpty -->
  <testcase name="testIterator" time="0.001" classname="Test_8">
    <failure type="java.lang.UnsupportedOperationException">
      <![CDATA[java.lang.UnsupportedOperationException
	at Test_8.testIterator(Test_8.java:149)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testIterator -->
  <testcase name="testLast" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testLast()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testLast()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testLast -->
  <testcase name="testRemoveFirst" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testRemoveFirst()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testRemoveFirst()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveFirst -->
  <testcase name="testRemoveLast" time="0.007" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testRemoveLast()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testRemoveLast()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IllegalStateException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testRemoveLast -->
  <testcase name="testRemove_invalidElement" time="0.0" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [6] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [null]
	at TestCase.remove(TestCase.java:93)
	at Test_8.testRemove_invalidElement(Test_8.java:87)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidElement -->
  <testcase name="testRemove_invalidIndex" time="0.001" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [5] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [null]
	at TestCase.remove(TestCase.java:182)
	at Test_8.testRemove_invalidIndex(Test_8.java:209)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRemove_invalidIndex -->
  <testcase name="testSet" time="0.0" classname="Test_8">
    <failure type="org.testng.TestException" message="
Method Test_8.testSet()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Test_8.testSet()[pri:0, instance:Test_8@28feb3fa] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testSet -->
  <testcase name="testSize" time="0.0" classname="Test_8">
    <failure type="java.lang.AssertionError" message="expected [0] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [-1]
	at TestCase.size(TestCase.java:149)
	at Test_8.testSize(Test_8.java:137)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSize -->
</testsuite>
